const products = [
  {
    id: "1",
    name: "Thời Trang Nam",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Thời Trang Nữ",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Điện Thoại & Phụ Kiện",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  { id: "1", name: "Mẹ và bé", src: "", price: 100000, quantitySale: 1 },
  {
    id: "1",
    name: "Thiết bị điện tử",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Nhà cửa và đời sống",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Máy tính và laptop",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  { id: "1", name: "Sắc đẹp", src: "", price: 100000, quantitySale: 1 },
  {
    id: "1",
    name: "Máy ảnh và máy quay phim",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  { id: "1", name: "Sức khỏe", src: "", price: 100000, quantitySale: 1 },
  { id: "1", name: "Đồng hồ", src: "", price: 100000, quantitySale: 1 },
  { id: "1", name: "Giày dép nữ", src: "", price: 100000, quantitySale: 1 },
  {
    id: "1",
    name: "Giày dép nam",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  { id: "1", name: "Túi ví nữ", src: "", price: 100000, quantitySale: 1 },
  {
    id: "1",
    name: "Thiết bị điện gia dụng",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Phụ kiện và trang sức nữ",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Thể thao và du lịch",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Phụ kiện và trang sức nữ",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Thiết bị điện gia dụng",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Phụ kiện và trang sức nữ",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Thể thao và du lịch",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
  {
    id: "1",
    name: "Phụ kiện và trang sức nữ",
    src: "",
    price: 100000,
    quantitySale: 1,
  },
];
export { products };
